module Rpc.Autogen.XenmgrConst (
    eMANAGED_DISKTYPE_NONE
  , eMANAGED_DISKTYPE_SYSTEM
  , eMANAGED_DISKTYPE_APPLICATION
  , eMANAGED_DISKTYPE_USER
  , eS3_MODE_PV
  , eS3_MODE_IGNORE
  , eS3_MODE_RESTART
  , eS3_MODE_SNAPSHOT
  , eS4_MODE_PV
  , eS4_MODE_IGNORE
  , eS4_MODE_RESTART
  , eS4_MODE_SNAPSHOT
  , eVM_STATE_CREATING
  , eVM_STATE_RUNNING
  , eVM_STATE_STOPPING
  , eVM_STATE_STOPPED
  , eVM_STATE_LOCKED
  , eVM_STATE_REBOOTING
  , eVM_STATE_REBOOTED
  , eVM_STATE_SUSPENDING
  , eVM_STATE_SUSPENDED
  , eVM_STATE_RESTORING
  , eVM_STATE_PAUSED
) where

import Data.String
import Data.Word
import Data.Int

eMANAGED_DISKTYPE_NONE :: String
eMANAGED_DISKTYPE_NONE = ""

eMANAGED_DISKTYPE_SYSTEM :: String
eMANAGED_DISKTYPE_SYSTEM = "system"

eMANAGED_DISKTYPE_APPLICATION :: String
eMANAGED_DISKTYPE_APPLICATION = "application"

eMANAGED_DISKTYPE_USER :: String
eMANAGED_DISKTYPE_USER = "user"

eS3_MODE_PV :: String
eS3_MODE_PV = "pv"

eS3_MODE_IGNORE :: String
eS3_MODE_IGNORE = "ignore"

eS3_MODE_RESTART :: String
eS3_MODE_RESTART = "restart"

eS3_MODE_SNAPSHOT :: String
eS3_MODE_SNAPSHOT = "snapshot"

eS4_MODE_PV :: String
eS4_MODE_PV = "pv"

eS4_MODE_IGNORE :: String
eS4_MODE_IGNORE = "ignore"

eS4_MODE_RESTART :: String
eS4_MODE_RESTART = "restart"

eS4_MODE_SNAPSHOT :: String
eS4_MODE_SNAPSHOT = "snapshot"

eVM_STATE_CREATING :: String
eVM_STATE_CREATING = "creating"

eVM_STATE_RUNNING :: String
eVM_STATE_RUNNING = "running"

eVM_STATE_STOPPING :: String
eVM_STATE_STOPPING = "stopping"

eVM_STATE_STOPPED :: String
eVM_STATE_STOPPED = "stopped"

eVM_STATE_LOCKED :: String
eVM_STATE_LOCKED = "locked"

eVM_STATE_REBOOTING :: String
eVM_STATE_REBOOTING = "rebooting"

eVM_STATE_REBOOTED :: String
eVM_STATE_REBOOTED = "rebooted"

eVM_STATE_SUSPENDING :: String
eVM_STATE_SUSPENDING = "suspending"

eVM_STATE_SUSPENDED :: String
eVM_STATE_SUSPENDED = "suspended"

eVM_STATE_RESTORING :: String
eVM_STATE_RESTORING = "restoring"

eVM_STATE_PAUSED :: String
eVM_STATE_PAUSED = "paused"

